### ISSUE TITLE
The lessOrEqual function for intervals is incorrect and there is an off by one error when loading elf binaries

### ISSUE THREAD

**Issue by tpetersonkth** [jkinder/jakstab#10]
For more info on the off-by-one error: https://github.com/pythonpsycho1337/Alternating-Control-Flow-Reconstruction/issues/3
For more info on the LessOrEqual bug in the strided interval domain: https://github.com/pythonpsycho1337/Alternating-Control-Flow-Reconstruction/issues/4

I have fixed both of the bugs in my fork of the repository: https://github.com/tpetersonkth/AlternatingControlFlowReconstruction

**Comment by jkinder** [comment]
Thanks for the fix, I've integrated it just now!
