### ISSUE TITLE
Basic block and edges in the CFG that represent no instruction in the binary

### ISSUE THREAD

**Issue by riyadparvez** [jkinder/jakstab#2]
I'm using jakstab to extract CFG for the binaries in coreutils. Jakstab is working great except it produces some basic blocks and edges that don't correspond to any instruction in the binary. Is there any way to fix this? I would appreciate some pointers and happy to submit a PR.

**Comment by jkinder** [comment]
Jakstab is designed to compute an over-approximation, so it will necessarily sometimes include basic blocks or branches that are actually infeasible. This depends very much on the type of abstract domain you are using. Your best bet is to try and use a more precise abstract domain (e.g., by increasing the bound in BAT).
