### ISSUE TITLE
Running Jakstab on jumptable.exe

### ISSUE THREAD

**Issue by cojocar** [jkinder/jakstab#6]
The documentation states that in order to analyze the `jumptable.exe` input example, Jakstab should run with `jakstab -m input/jumptable.exe --cpa xfi`. I'm getting the following error:

```
jakstab -m input\bin\juptable.exe --cpa xfi
=======================================================================
   Jakstab 0.8.4-devel 
...
Reading machine specification from pentium.ssl.
Parsing input\bin\jumptable.exe...
Finished parsing executable.
Initializing control flow reconstruction.
--- Using Bounded Address Tracking
--- Using Forward substitution
No analysis corresponds to letter "i"!
```

Is the interval analysis used somewhere? I can see that there is some code related to this.

**Comment by chostelet** [comment]
Hello,

Having the exact same issue. Anyway to get intervals classes being compiled?

**Comment by chostelet** [comment]
Answering to my own question.
I'm usin Bash for Windows 10 and had to update script "compile.sh" to use an absolute path for "JSCLASSPATH". Here is the modified shell script.
---
#!/bin/bash
CWD=`/bin/pwd`
JSCLASSPATH=$CWD/lib/antlr.jar:$CWD/lib/google-collect-1.0.jar:$CWD/lib/javabdd-1.0b2.jar
case `uname` in
    CYGWIN*)
        JSCLASSPATH=`cygpath -p -d "$JSCLASSPATH"`
        ;;
    *)
esac
if [ ! -d bin ]; then mkdir bin; fi
javac -d bin/ `find -L src/ -name '*.java'` -cp ${JSCLASSPATH}
read#!/bin/bash
CWD=`/bin/pwd`
JSCLASSPATH=$CWD/lib/antlr.jar:$CWD/lib/google-collect-1.0.jar:$CWD/lib/javabdd-1.0b2.jar
case `uname` in
    CYGWIN*)
        JSCLASSPATH=`cygpath -p -d "$JSCLASSPATH"`
        ;;
    *)
esac
if [ ! -d bin ]; then mkdir bin; fi
javac -d bin/ `find -L src/ -name '*.java'` -cp ${JSCLASSPATH}
---

This permits to compile ALL java sources and get ALL the analysis classes (interval included)
